### ISSUE TITLE
Issue when transitionning back

### ISSUE THREAD

**Issue by Athosone** [HeroTransitions/Hero#338]
Hello,

I setup an animation from a collection view cell to a UIViewController. But when I get back the image in the cell are hidden, the Hero plugin shows that they are "behind" the source view controller and then when animation finishes they come back to their normal positions.

I don't do anything special. I set a heroID on source imageview and destination imageview.

![animation](https://user-images.githubusercontent.com/9287010/33285245-05bf2696-d3b2-11e7-9620-14ecd81d4088.gif)

**Comment by Athosone** [comment]
It is important to note that the image in the cell is loaded asynchronously. When I trier with a local image it works well

**Comment by lkzhao** [comment]
If the image is loaded asynchronously, then the snapshot captured at the start of the transition will not contain the image content. You can try using `.useNoSnapshot` modifier to make Hero use your view for the transition instead of creating a snapshot. This way, the image can be loaded in the middle of the transition. Keep in mind that `.useNoSnapshot` is harder to work with. You shouldn't modify the frame or change its superview during the transition, otherwise it will create weird effects.

**Comment by kuyazee** [comment]
Did @lkzhao's suggestion work?
