### ISSUE TITLE
Interactive dismiss view controller

### ISSUE THREAD

**Issue by nhatquangz** [HeroTransitions/Hero#388]
When I implement pangesture to dismiss view controller (swipe right to dismiss feature), i set whold view to apply function:
Hero.shared.apply(modifiers: [.position(currentPos)], to: self.view)
The view position is updated by transition animation (i set dismiss animation is .pull) rather than by my finger.
I think it may be cause by process of animation dont match with gesture.
I set progress: let progress = translation.x / (SCREEN_WIDTH / 2)
Hope some one help me!

Video:
https://drive.google.com/file/d/14Y5K98SHt5meOHeKoKHEZrgYjjbXxNlU/view?usp=sharing

**Comment by lkzhao** [comment]
It is because that the pull animation doesn't use a linear timing function. The timing function that it uses is probably easeInOut which accelerated at the start and decelerate near the end. 

There are two ways you can make the view move with your finger.
1. call `Hero.shared.apply(.translate(x: progress * SCREEN_WIDTH), to: view)` in your gesture handler.
2. do not use `.pull` animation and apply your own modifier with a linear timing function:
`view.hero.modifiers = [.translate(x: SCREEN_WIDTH), .timingFunction(.linear)]`

**Comment by NhatQuangZ** [comment]
The first option work very well 👍 
The second option also work but .linear make animation look not good.
Thank you for your support and your lib, it bring more powerfull for ios developers.
P/s: In future, i hope you can make some thing like transition between UIViews, not only between ViewControllers.  It will make this lib very very powerful.
