### ISSUE TITLE
Text Warps On Animation

### ISSUE THREAD

**Issue by JayBone16** [HeroTransitions/Hero#409]
When animating a button, label, anything with text. The text becomes stretched.
I have linked everything properly using ID's. I have used many modifiers but nothing has seemed to work so far.

Please help! I have been trying to troubleshoot this for days.
I also have referenced back to your appstore git and it hasn't worked for me.

**Comment by lkzhao** [comment]
It is because hero tasked a snapshot at the beginning of the animation. Then use the snapshot to animate. You can try the .useNoSnapshot modifier which forces hero to not use any snapshot. But becareful that it might break your auto layout if you use it, since hero will take the label from its superview and inserted into a global container view during the transition.
