### ISSUE TITLE
"Library not loaded" Error

### ISSUE THREAD

**Issue by invisible66** [HeroTransitions/Hero#510]
I am getting this error. How can i fixed this? :( It's says `image not found` but i don't know which image not found

```
dyld: Library not loaded: @rpath/Hero.framework/Hero
  Referenced from: /var/containers/Bundle/Application/A25E669E-1467-4867-385E-37FE34375B0E/myApp.app/myApp
  Reason: image not found
```

**Comment by SD10** [comment]
@invisible66 How are you installing Hero?

**Comment by invisible66** [comment]
I tried both of cocoapod and manual installation but i got same error.

I can install Hero after update my pod (`pod update`).

**Comment by thefabbulus** [comment]
@SD10 @JoeMatt I'm getting the same error when installing via SPM:

`.package(url: "https://github.com/HeroTransitions/Hero.git", .upToNextMajor(from: "1.6.1"))`

It's only crashing on a real device, but not on the emulator.

It is working great when installed with `exact version = 1.6.0`, so it looks like the issue was introduced (again?) with [Swift 5 support](https://github.com/HeroTransitions/Hero/releases/tag/1.6.0).

Thanks for the amazing work!

**Comment by andrebng** [comment]
Using SPM to install with Swift 5, got a similar issue (maybe?). It crashes on opening the app and only when its distributed. What I found in the logs:

DYLD; dyld: Using shared cache: ... dependent dylib '@rpath/Hero.framework/Hero' not found for 'private/var/containers/Bundle/Application/....app/Frameworks/Hero.framework/Hero'

**Comment by ucookteam** [comment]
having same issue

**Comment by andrebng** [comment]
I solved my issue by setting the SPM installed Hero framework from "Do not embed" to "Embed and Sign" under the targets settings, but might be related to another issue I had

**Comment by the-scott-davis** [comment]
The solutuon provided by @andrebng also worked for me.
