### ISSUE TITLE
Hero 1.4.0 from the branch swift-4.2 does not work with UITests in my Objective-C application

### ISSUE THREAD

**Issue by RomanPodymov** [HeroTransitions/Hero#545]
Hello.
Thanks for your library, I really like it.
Usually I use it with Swift, but now I want to try it with Objective-C. After update from Xcode v.9.4.1 to v.10.0 I cannot run UITests in my application, I receive the following error:
`Library not loaded: @rpath/libswiftCore.dylib
 Referenced from: /private/var/containers/Bundle/Application/SOME_LETTERS/UITests-Runner.app/PlugIns/UITests.xctest/Frameworks/Hero.framework/Hero
 Reason: image not found)`.
I added `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;` to all targets in my application but it does not solve the problem. Could you please tell me how can I use Hero 1.4.0 with Objective-C?

**Comment by ugenlik** [comment]
+1 I get exact same error.

**Comment by ugenlik** [comment]
@RomanPodymov I have just solved it, here is my solution 

- Delete Derived Data
- Delete Pods Folder
- Delete Podfile.lock
- Update podfile hero to swift 4.2 commit  `pod 'Hero' , :git => 'https://github.com/HeroTransitions/Hero.git', :commit => '85be93ff80247296ee17f340bef73cfeb18c9fa0'`

then

- `pod deintegrate`

followed by

- `pod install`

then 

- open the  `xcworkspace` file klet Xcode finish indexing, it sounds silly but otherwise it throws error because Deriveddata is deleted... 

- then switch back to Legacy Build System (File > Project/Workspace Settings)

then run your UI tests, it works....

**Comment by RomanPodymov** [comment]
Hello @ugenlik 
Thanks for advice. However your solution does not work for me because I use Travis CI and currently I cannot delete derived data. Maybe there is a more flexible solution for this issue?

**Comment by ugenlik** [comment]
@RomanPodymov most CI systems delete Derived Data before running builds. Do you use Fastlane?

**Comment by RomanPodymov** [comment]
@ugenlik I can try to run UI tests with Fastlane.

**Comment by ugenlik** [comment]
@RomanPodymov  in your xcode change (File > Project/Workspace Settings) to Legacy Build System then I believe when do your commit and run it on Travis it should be good, also Fastlane has `clean` command , it works in Jenkins but I have never used Travis before so can't say anything for that

**Comment by RomanPodymov** [comment]
@ugenlik I switched to the Legacy Build System and I still cannot create a build with Travis CI. I need to try it with Fastlane.

**Comment by ugenlik** [comment]
@RomanPodymov did you try Legacy Build Sytem locally on your machine? 

I have just tested my changes on Jenkins with Fastlane , it failed first then I realized, build settings are ignore because of my .gitignore file

so in fastlane I passed

``
scan(
        xcargs: "-UseNewBuildSystem=NO")
```

then it worked.

**Comment by RomanPodymov** [comment]
Hello @ugenlik 
Now it works, thank you for help. This is [a link to the project](https://github.com/RomanPodymov/NotesApplication) where I was able to reproduce this problem.
