### ISSUE TITLE
How to use Hero for a splash screen

### ISSUE THREAD

**Issue by nrgbistro** [HeroTransitions/Hero#577]
## What did you do?

I am trying to make a splash screen for my app. I am using a viewController (called splashScreen) connected to a tabBarController. Currently, I have this code in the splashScreenVC:

        let vc1 = SplashScreenViewController()
        let vc2 = tabBarController
        
        vc1.hero.isEnabled = true
        vc2?.hero.isEnabled = true
        
        vc1.hero.modalAnimationType = .autoReverse(presenting: .pull(direction: .right))
        
        present(vc2!, animated: true, completion: nil)

This returns an error, because vc2 returns nil but I cannot figure out why or how I should select my first view within the viewController.

## What did you expect to happen?

I expected to see some sort of transition between my views.

##  What happened instead?

vc2 returns nil, and therefore the present command cannot process.

## General Information

* Hero Version: v1.4.0

* iOS Version(s): 11

* Swift Version: 10.1

* Devices/Simulators: iPhone 7 plus

[setup of storyboards](https://pasteboard.co/HYR0PGZ.png)

## Demo Project

[Harriton App](https://github.com/nrgbistro/Harriton-App)

**Comment by deanWombourne** [comment]
Hi,

This isn't a bug in Hero, it's an issue with your storyboard layout. The property `self.tabBarController` on a `UIViewController` refers to the tab bar controller you are currently inside. However, your splash screen view controller isn't in a tab bar controller, so that property is `nil`.

To get this to work with your storyboard, you wouldn't manually present the tab bar controller, you would perform the segue using `self.performSegue(withIdentifier: "splashScreen", sender: self)`.

you also can't configure the tab bar controller inside the splash screen view controller because it doesn't exist yet :) You can set the hero isEnabled to true inside the storyboard though.
