### ISSUE TITLE
[Proposal] Seems this repo is not maintained any more, start working on a new fork?

### ISSUE THREAD

**Issue by shuoli84** [HeroTransitions/Hero#597]
Though this project stays in trending constantly, it is not maintained for a while. Thanks for the great work.
I tried to ping @lkzhao @SD10 , original author and the last active maintainer, but receives no response yet. Seems it is time to start working on a fork? Anyone already maintaining active fork?

**Comment by danielsaidi** [comment]
I think that they at least should add more maintainers, so that we can get some small things fixed, like code structure changes that remove build warnings on CI etc.

You can use my fork if you have the same problems, but I'd rather be helping out here than having a personal fork :)

https://github.com/danielsaidi/Hero

**Comment by kuyazee** [comment]
Resolved in #606
